# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2c58548f570ec3d95fba85682e6cf0c3a16f3367d3a8b5394c2d871c3722da25120aedc100554977c9401bf3eb9f7b3a9158b3e441d427849c1237a22b24142d

test:
  secret_key_base: 12fe76efd2841b8b3f906b2610248066b04e2f78cdf506de4420e16868425d8219b0197ec199f2367470d5dc7ad4f22a6c889db301e2218efeca155b8a3149fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
